import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseAttrs, extractHead, listTags, pluginAssets, isWordPress } from '../src/html.js';
import { cacheVerdict } from '../src/cache.js';
import { viewportPosition, renderBlocking, recaptcha, compression, lcpHint } from '../src/checks.js';

const res = (body, headers = {}, ttfbMs = 100) => ({ body, headers, ttfbMs, totalMs: ttfbMs, status: 200 });

test('parseAttrs reads quoted, unquoted and boolean attributes', () => {
  assert.deepEqual(parseAttrs('<script src="/a.js" defer data-x=1>'), { src: '/a.js', defer: '', 'data-x': '1' });
  assert.deepEqual(parseAttrs("<meta name='viewport' content='width=device-width'>"), { name: 'viewport', content: 'width=device-width' });
});

test('extractHead and listTags keep document order', () => {
  const html = '<html><head><link rel="stylesheet" href="a.css"><meta name="viewport"></head><body><img src="x"></body></html>';
  const head = extractHead(html);
  assert.equal(listTags(head).map(t => t.name).join(','), 'link,meta');
});

test('pluginAssets groups files by plugin slug', () => {
  const html = '<script src="/wp-content/plugins/foo/a.js"></script><link rel="stylesheet" href="/wp-content/plugins/foo/b.css"><script src="/wp-content/plugins/bar/c.js?ver=1"></script>';
  assert.deepEqual(Object.fromEntries(Object.entries(pluginAssets(html)).map(([k, v]) => [k, v.length])), { foo: 2, bar: 1 });
  assert.equal(isWordPress(html), true);
});

test('cacheVerdict understands Cloudflare and WP Super Cache', () => {
  assert.equal(cacheVerdict(res('', { 'cf-cache-status': 'HIT' })).hit, true);
  assert.equal(cacheVerdict(res('', { 'cf-cache-status': 'DYNAMIC' })).hit, false);
  assert.equal(cacheVerdict(res('<!-- Dynamic page generated in 0.4 seconds. -->')).hit, false);
  assert.equal(cacheVerdict(res('<!-- Dynamic page generated in 0.4 seconds. --><!-- Cached page generated by WP-Super-Cache on 2026-10-06 -->')).hit, true);
  assert.equal(cacheVerdict(res('', { age: '120' })).hit, true);
  assert.equal(cacheVerdict(res('')).hit, null);
});

test('viewport after a stylesheet is a warning, missing is a failure', () => {
  const late = '<head><link rel="stylesheet" href="a.css"><meta name="viewport" content="width=device-width"></head>';
  const early = '<head><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="a.css"></head>';
  assert.equal(viewportPosition({ warm: res(late) }).status, 'warn');
  assert.equal(viewportPosition({ warm: res(early) }).status, 'pass');
  assert.equal(viewportPosition({ warm: res('<head></head>') }).status, 'fail');
});

test('render-blocking counts head scripts without async/defer/module', () => {
  const head = '<head>' + '<script src="/a.js"></script>'.repeat(4) + '<script src="/b.js" defer></script><script type="module" src="/c.js"></script></head>';
  const r = renderBlocking({ warm: res(head) });
  assert.equal(r.status, 'warn');
  assert.match(r.summary, /^4 blocking/);
});

test('reCAPTCHA without a form is a warning', () => {
  const tag = '<script src="https://www.google.com/recaptcha/api.js?render=x"></script>';
  assert.equal(recaptcha({ warm: res(tag) }).status, 'warn');
  assert.equal(recaptcha({ warm: res(tag + '<form></form>') }).status, 'info');
  assert.equal(recaptcha({ warm: res('<p>hi</p>') }).status, 'pass');
});

test('compression and image priority', () => {
  const big = 'x'.repeat(20 * 1024);
  assert.equal(compression({ warm: res(big) }).status, 'fail');
  assert.equal(compression({ warm: res(big, { 'content-encoding': 'br' }) }).status, 'pass');
  assert.equal(lcpHint({ warm: res('<img src="hero.webp" fetchpriority="high">') }).status, 'pass');
  assert.equal(lcpHint({ warm: res('<img src="hero.webp">') }).status, 'warn');
});
