import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseAttrs, extractHead, listTags, pluginAssets, isWordPress } from '../src/html.js';
import { cacheVerdict } from '../src/cache.js';
import { viewportPosition, renderBlocking, recaptcha, compression, lcpHint, notFound, runChecks, pageCache, mobileCache } from '../src/checks.js';
import { consentCookie } from '../src/consent.js';
import { wordpressBase } from '../src/wpbase.js';

const res = (body, headers = {}, ttfbMs = 100) => ({ body, headers, ttfbMs, totalMs: ttfbMs, status: 200 });

test('parseAttrs reads quoted, unquoted and boolean attributes', () => {
  assert.deepEqual(parseAttrs('<script src="/a.js" defer data-x=1>'), { src: '/a.js', defer: '', 'data-x': '1' });
  assert.deepEqual(parseAttrs("<meta name='viewport' content='width=device-width'>"), { name: 'viewport', content: 'width=device-width' });
});

test('extractHead and listTags keep document order', () => {
  const html = '<html><head><link rel="stylesheet" href="a.css"><meta name="viewport"></head><body><img src="x"></body></html>';
  const head = extractHead(html);
  assert.equal(listTags(head).map(t => t.name).join(','), 'link,meta');
});

test('pluginAssets groups files by plugin slug', () => {
  const html = '<script src="/wp-content/plugins/foo/a.js"></script><link rel="stylesheet" href="/wp-content/plugins/foo/b.css"><script src="/wp-content/plugins/bar/c.js?ver=1"></script>';
  assert.deepEqual(Object.fromEntries(Object.entries(pluginAssets(html)).map(([k, v]) => [k, v.length])), { foo: 2, bar: 1 });
  assert.equal(isWordPress(html), true);
});

test('cacheVerdict understands Cloudflare and WP Super Cache', () => {
  assert.equal(cacheVerdict(res('', { 'cf-cache-status': 'HIT' })).hit, true);
  assert.equal(cacheVerdict(res('', { 'cf-cache-status': 'BYPASS' })).hit, false);
  assert.equal(cacheVerdict(res('', { 'cf-cache-status': 'DYNAMIC' })).hit, null, 'DYNAMIC says nothing about a cache on the server');
  assert.equal(cacheVerdict(res('<!-- Dynamic page generated in 0.4 seconds. -->')).hit, false);
  assert.equal(cacheVerdict(res('<!-- Dynamic page generated in 0.4 seconds. --><!-- Cached page generated by WP-Super-Cache on 2026-10-06 -->')).hit, true);
  assert.equal(cacheVerdict(res('', { age: '120' })).hit, true);
  assert.equal(cacheVerdict(res('')).hit, null);
});

test('cacheVerdict understands CDNs and managed hosts outside WordPress', () => {
  const v = h => cacheVerdict(res('', h));
  assert.deepEqual([v({ 'x-vercel-cache': 'HIT' }).hit, v({ 'x-vercel-cache': 'MISS' }).hit], [true, false]);
  assert.equal(v({ 'cache-status': '"Netlify Edge"; hit' }).hit, true);
  assert.equal(v({ 'cache-status': '"Netlify Edge"; fwd=miss' }).hit, false);
  assert.deepEqual(v({ 'cache-status': '"Netlify Edge"; hit' }).sources, ['Netlify Edge (Cache-Status)']);
  assert.equal(v({ 'x-cache': 'Hit from cloudfront' }).sources[0], 'CloudFront');
  assert.equal(v({ 'x-cache': 'TCP_MEM_HIT from a23-1-2-3' }).hit, true);
  assert.equal(v({ 'x-cache': 'MISS, HIT', 'x-served-by': 'cache-fra-1, cache-mxp-2' }).hit, true, 'Fastly: the last tier is the edge');
  assert.equal(v({ 'x-cache': 'HIT, MISS', 'x-served-by': 'cache-fra-1, cache-mxp-2' }).hit, false);
  assert.deepEqual([v({ 'x-varnish': '123 456' }).hit, v({ 'x-varnish': '789' }).hit], [true, false]);
  assert.equal(v({ 'x-kinsta-cache': 'HIT' }).sources[0], 'Kinsta cache');
});

test('non-WordPress sites skip the plugin check and get generic fixes', () => {
  const page = res('<head><meta name="viewport" content="width=device-width"></head>', { 'cf-cache-status': 'MISS' }, 2500);
  const data = { first: page, warm: page, cookie: page, utm: page, mobileFirst: page, mobileWarm: page, notFound: null, notFoundWarm: null, pages: [], consent: { name: null }, isWp: false };
  const results = runChecks(data);
  assert.equal(results.some(r => r.id === 'plugin-assets'), false);
  assert.doesNotMatch(results.find(r => r.id === 'page-cache').fix, /WP Super Cache/);
});

test('field test regressions (developer.wordpress.org, wordpress.com, Wikipedia, Vercel)', () => {
  const r = (headers, body = '', t = 100) => res(body, headers, t);
  // A miss on the repeat visit while the phone got a HIT: the cache exists.
  const pc = pageCache({ first: r({}), warm: r({ 'x-nc': 'MISS dca 2' }), cookie: r({ 'x-nc': 'MISS' }), utm: r({}), mobileWarm: r({ 'x-nc': 'HIT dca 2' }) });
  assert.equal(pc.status, 'warn');
  assert.match(pc.summary, /served other visits/);
  // BYPASS means a cache that skips the page, not "no cache".
  const bp = pageCache({ first: r({}), warm: r({ 'x-ac': '15.mxp _dca BYPASS' }), cookie: r({}), utm: r({}) });
  assert.match(bp.summary, /skips this page \(BYPASS\)/);
  // Wikipedia x-cache format.
  assert.equal(cacheVerdict(r({ 'x-cache': 'cp6013 hit, cp6016 hit/2' })).hit, true);
  // Vary: User-Agent with both visits cached is information, not a warning.
  const vary = { 'cf-cache-status': 'HIT', vary: 'accept-encoding,user-agent' };
  assert.equal(mobileCache({ warm: r(vary), mobileWarm: r(vary) }).status, 'info');
  // Unknown URLs that land on a login page are an app pattern, not a soft 404.
  const nf = { status: 200, headers: {}, body: '', url: 'https://app.test/login?next=/x', requestedUrl: 'https://app.test/wp-doctor-missing-1/' };
  assert.equal(notFound({ notFound: nf, notFoundWarm: nf }).status, 'info');
});

test('advice follows the cache layer, spares the consent manager, and info results carry no fix', () => {
  const r = (headers, body = '', t = 100) => res(body, headers, t);
  const pc = pageCache({ first: r({ 'cf-cache-status': 'HIT' }), warm: r({ 'cf-cache-status': 'HIT' }), cookie: r({ 'cf-cache-status': 'HIT' }), utm: r({ 'cf-cache-status': 'MISS' }, '', 1200) });
  assert.match(pc.fix, /Cloudflare Cache Rule/);
  assert.doesNotMatch(pc.fix, /WP Super Cache/);
  const head = '<head><script src="https://cs.iubenda.com/autoblocking/1.js"></script><script src="https://cdn.iubenda.com/cs/tcf/stub-v2.js"></script>' + '<script src="/a.js"></script>'.repeat(2) + '</head>';
  const rb = renderBlocking({ warm: r({}, head) });
  assert.equal(rb.status, 'pass');
  assert.match(rb.summary, /^2 blocking scripts/);
  assert.match(rb.details.join(' '), /consent manager: 2 scripts/);
  const vary = { 'cf-cache-status': 'HIT', vary: 'user-agent' };
  assert.equal(mobileCache({ warm: r(vary), mobileWarm: r(vary) }).fix, undefined);
});

test('viewport after a stylesheet is a warning, missing is a failure', () => {
  const late = '<head><link rel="stylesheet" href="a.css"><meta name="viewport" content="width=device-width"></head>';
  const early = '<head><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="a.css"></head>';
  assert.equal(viewportPosition({ warm: res(late) }).status, 'warn');
  assert.equal(viewportPosition({ warm: res(early) }).status, 'pass');
  assert.equal(viewportPosition({ warm: res('<head></head>') }).status, 'fail');
});

test('render-blocking counts head scripts without async/defer/module', () => {
  const head = '<head>' + '<script src="/a.js"></script>'.repeat(4) + '<script src="/b.js" defer></script><script type="module" src="/c.js"></script></head>';
  const r = renderBlocking({ warm: res(head) });
  assert.equal(r.status, 'warn');
  assert.match(r.summary, /^4 blocking/);
});

test('reCAPTCHA without a form is a warning', () => {
  const tag = '<script src="https://www.google.com/recaptcha/api.js?render=x"></script>';
  assert.equal(recaptcha({ warm: res(tag) }).status, 'warn');
  assert.equal(recaptcha({ warm: res(tag + '<form></form>') }).status, 'info');
  assert.equal(recaptcha({ warm: res('<p>hi</p>') }).status, 'pass');
});

test('consentCookie recognises common banners and falls back to a generic cookie', () => {
  assert.equal(consentCookie('<script src="https://cdn.iubenda.com/cs/iubenda_cs.js"></script>"siteId":987').cookie.startsWith('_iub_cs-987='), true);
  assert.equal(consentCookie('<script src="https://consent.cookiebot.com/uc.js"></script>').name, 'Cookiebot');
  assert.equal(consentCookie('<div id="cmplz-cookiebanner-container"></div><script>var complianz = {}</script>').name, 'Complianz');
  assert.equal(consentCookie('<script src="/wp-content/plugins/complianz-gdpr/cookiebanner/js/complianz.min.js"></script>').name, 'Complianz');
  assert.equal(consentCookie('<p>We compared iubenda and Cookiebot in this article.</p>').name, null, 'text that mentions a banner is not a banner');
  assert.equal(consentCookie('<link rel="preconnect" href="https://cdn.iubenda.com"><div id="cmplz-cookiebanner-container"></div>').name, 'Complianz', 'a preconnect hint is not a banner');
  assert.equal(consentCookie('<p>no banner</p>').name, null);
});

test('notFound flags soft 404s and long-cached 404s', () => {
  const nf = (status, headers = {}) => ({ status, headers, url: 'https://x.test/missing/', requestedUrl: 'https://x.test/missing/', body: '', ttfbMs: 50 });
  assert.equal(notFound({ notFound: nf(200), notFoundWarm: nf(200) }).status, 'fail');
  assert.equal(notFound({ notFound: nf(404), notFoundWarm: nf(404, { 'cf-cache-status': 'HIT', 'cache-control': 'max-age=86400' }) }).status, 'warn');
  assert.equal(notFound({ notFound: nf(404), notFoundWarm: nf(404, { 'cf-cache-status': 'HIT', 'cache-control': 'max-age=60' }) }).status, 'pass');
});

test('reCAPTCHA referenced only in inline code is loaded on demand', () => {
  const inline = '<form></form><script>function load(){var s=document.createElement("script");s.src="https://www.google.com/recaptcha/api.js?render=x";}</script>';
  const r = recaptcha({ warm: res(inline) });
  assert.equal(r.status, 'pass');
  assert.match(r.summary, /on demand/);
});

test('wordpressBase finds a subfolder install from the REST API link', () => {
  const html = '<link rel="https://api.w.org/" href="https://www.example.com/info/wp-json/">';
  assert.equal(wordpressBase(html, 'https://www.example.com/info/'), 'https://www.example.com/info/');
  assert.equal(wordpressBase('<p></p>', 'https://www.example.com/a/b/'), 'https://www.example.com/');
});

test('iubenda embed widgets and autoblocking are recognised', () => {
  assert.equal(consentCookie('<script src="https://embeds.iubenda.com/widgets/9de7cf15-dcf3.js"></script>').name, 'iubenda');
  assert.match(consentCookie('<script src="https://cs.iubenda.com/autoblocking/2582173.js"></script>').cookie, /^_iub_cs-2582173=/);
});

test('a blocked site stops at reachability instead of analysing the error page', () => {
  const err = { status: 403, headers: { 'x-cache': 'Error from cloudfront' }, body: '<title>ERROR</title>', ttfbMs: 80 };
  const results = runChecks({ first: err, warm: err, pages: [] });
  assert.equal(results.length, 1);
  assert.equal(results[0].id, 'reachability');
  assert.match(results[0].summary, /blocks automated requests.*cloudfront/);
  const challenge = { status: 200, headers: {}, body: '<html><head><title>Just a moment...</title></head></html>', ttfbMs: 80 };
  assert.equal(runChecks({ first: challenge, warm: challenge, pages: [] })[0].id, 'reachability');
});

test('compression and image priority', () => {
  const big = 'x'.repeat(20 * 1024);
  assert.equal(compression({ warm: res(big) }).status, 'fail');
  assert.equal(compression({ warm: res(big, { 'content-encoding': 'br' }) }).status, 'pass');
  assert.equal(lcpHint({ warm: res('<img src="hero.webp" fetchpriority="high">') }).status, 'pass');
  assert.equal(lcpHint({ warm: res('<img src="hero.webp">') }).status, 'warn');
});
