// Reads a response and tells whether it was served from a cache, and by which layer.
// hit: true (served from cache), false (generated or missed), null (no evidence either way).

const HEADER_RULES = [
  { header: 'cf-cache-status', source: 'Cloudflare', hit: v => /^(HIT|STALE|REVALIDATED|UPDATING)$/i.test(v), miss: v => /^(MISS|EXPIRED|BYPASS|DYNAMIC)$/i.test(v) },
  { header: 'x-litespeed-cache', source: 'LiteSpeed Cache', hit: v => /^hit/i.test(v), miss: v => /^miss/i.test(v) },
  { header: 'x-proxy-cache', source: 'Nginx proxy cache', hit: v => /HIT/i.test(v), miss: v => /MISS|BYPASS|EXPIRED/i.test(v) },
  { header: 'x-cache-status', source: 'Nginx cache', hit: v => /HIT/i.test(v), miss: v => /MISS|BYPASS|EXPIRED/i.test(v) },
  { header: 'x-fastcgi-cache', source: 'FastCGI cache', hit: v => /HIT/i.test(v), miss: v => /MISS|BYPASS|EXPIRED/i.test(v) },
  { header: 'x-nginx-cache', source: 'Nginx cache', hit: v => /HIT/i.test(v), miss: v => /MISS|BYPASS|EXPIRED/i.test(v) },
  { header: 'x-nc', source: 'Automattic nginx cache', hit: v => /^HIT/i.test(v), miss: v => /^(MISS|EXPIRED|BYPASS)/i.test(v) },
  { header: 'x-cache', source: 'CDN/proxy cache', hit: v => /\bHIT\b/i.test(v), miss: v => /\bMISS\b/i.test(v) },
];

const BODY_RULES = [
  { re: /Cached page generated by WP-Super-Cache/i, source: 'WP Super Cache', hit: true },
  { re: /Dynamic page generated in [\d.]+ seconds/i, notIf: /Cached page generated by WP-Super-Cache/i, source: 'WP Super Cache', hit: false },
  { re: /Served from:[^>]*W3 Total Cache/i, source: 'W3 Total Cache', hit: true },
  { re: /Page Caching using [^>]*(?:\(Page is not cacheable|\(User is logged in)/i, source: 'W3 Total Cache', hit: false },
  { re: /This file was generated by WP Rocket/i, source: 'WP Rocket', hit: true },
  { re: /Cache served by (?:Simple Cache|Cache Enabler)/i, source: 'Cache plugin', hit: true },
  { re: /Page generated by LiteSpeed Cache/i, source: 'LiteSpeed Cache', hit: null },
];

export function cacheVerdict(res) {
  const evidence = [];
  let hit = null;
  const sources = new Set();

  for (const rule of HEADER_RULES) {
    const value = res.headers[rule.header];
    if (value === undefined) continue;
    sources.add(rule.source);
    evidence.push(`${rule.header}: ${value}`);
    if (rule.hit(value)) hit = true;
    else if (rule.miss(value) && hit !== true) hit = false;
  }

  for (const rule of BODY_RULES) {
    if (!rule.re.test(res.body)) continue;
    if (rule.notIf && rule.notIf.test(res.body)) continue;
    sources.add(rule.source);
    evidence.push(`HTML comment: ${rule.source}`);
    if (rule.hit === true) hit = true;
    else if (rule.hit === false && hit !== true) hit = false;
  }

  const age = Number(res.headers.age);
  if (Number.isFinite(age) && age > 0) {
    evidence.push(`age: ${age}`);
    if (hit === null) hit = true;
  }

  return { hit, sources: [...sources], evidence };
}

// True when the response tells shared caches not to store it.
export function isUncacheable(res) {
  const cc = res.headers['cache-control'] || '';
  return /\b(no-store|private)\b/i.test(cc) || Boolean(res.headers['set-cookie']);
}
