import { plural } from './report.js';

// A single self-contained HTML file: no external CSS, fonts or scripts, so it can be
// e-mailed, attached to a ticket or opened offline.

const LABEL = { pass: 'Passed', warn: 'Warning', fail: 'Failed', info: 'Info' };
const ORDER = { fail: 0, warn: 1, info: 2, pass: 3 };

export function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}

export function htmlReport(url, results, { isWp = true, checkedAt = new Date(), version = '' } = {}) {
  const count = s => results.filter(r => r.status === s).length;
  const sorted = [...results].sort((a, b) => ORDER[a.status] - ORDER[b.status]);
  const host = safeHost(url);
  const when = checkedAt.toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  const cards = sorted.map(r => `
    <article class="check ${r.status}">
      <header><span class="badge">${LABEL[r.status]}</span><h2>${escapeHtml(r.title)}</h2></header>
      <p>${escapeHtml(r.summary)}</p>
      ${r.details.length ? `<ul>${r.details.map(d => `<li>${escapeHtml(d)}</li>`).join('')}</ul>` : ''}
      ${r.fix ? `<p class="fix"><strong>How to fix:</strong> ${escapeHtml(r.fix)}</p>` : ''}
    </article>`).join('');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>wp-doctor report · ${escapeHtml(host)}</title>
<style>
  :root { --bg:#f6f7f9; --card:#fff; --text:#1b1f24; --muted:#5b6470; --line:#e3e6ea;
          --pass:#1a7f37; --warn:#9a6700; --fail:#c62828; --info:#0969da; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0d1117; --card:#161b22; --text:#e6edf3; --muted:#9198a1; --line:#30363d;
            --pass:#3fb950; --warn:#d29922; --fail:#f85149; --info:#58a6ff; }
  }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font:16px/1.5 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
  main { max-width: 860px; margin: 0 auto; padding: 32px 16px 48px; }
  h1 { font-size: 1.6rem; margin: 0 0 4px; overflow-wrap: anywhere; }
  .meta { color: var(--muted); margin: 0 0 20px; }
  .totals { display:flex; flex-wrap:wrap; gap:8px; margin: 0 0 24px; padding:0; list-style:none; }
  .totals li { background:var(--card); border:1px solid var(--line); border-radius:999px; padding:4px 12px; font-weight:600; }
  .totals .fail { color:var(--fail); } .totals .warn { color:var(--warn); } .totals .pass { color:var(--pass); }
  .check { background:var(--card); border:1px solid var(--line); border-left:4px solid var(--c); border-radius:8px; padding:16px 18px; margin:0 0 12px; }
  .check.pass { --c:var(--pass); } .check.warn { --c:var(--warn); } .check.fail { --c:var(--fail); } .check.info { --c:var(--info); }
  .check header { display:flex; align-items:center; gap:10px; flex-wrap:wrap; }
  .check h2 { font-size:1.05rem; margin:0; }
  .badge { color:var(--c); border:1px solid var(--c); border-radius:4px; font-size:.75rem; font-weight:700; padding:1px 6px; text-transform:uppercase; letter-spacing:.03em; }
  .check p { margin:8px 0 0; }
  .check ul { margin:8px 0 0; padding-left:20px; color:var(--muted); font-size:.92rem; overflow-wrap:anywhere; }
  .fix { background:var(--bg); border-radius:6px; padding:8px 10px; font-size:.95rem; }
  footer { color:var(--muted); font-size:.85rem; margin-top:28px; }
  a { color: var(--info); }
</style>
</head>
<body>
<main>
  <h1>${escapeHtml(host)}</h1>
  <p class="meta">${escapeHtml(url)} · checked ${escapeHtml(when)}${isWp ? '' : ' · does not look like WordPress'}</p>
  <ul class="totals">
    <li class="fail">${count('fail')} failed</li>
    <li class="warn">${plural(count('warn'), 'warning')}</li>
    <li class="pass">${count('pass')} passed</li>
  </ul>
  ${cards}
  <footer>Generated by <a href="https://github.com/andrea-sofia-dev/wp-doctor">wp-doctor</a>${version ? ' ' + escapeHtml(version) : ''}. Measured from one location at one moment: run it again before acting on borderline results.</footer>
</main>
</body>
</html>
`;
}

export function defaultReportName(url, date = new Date()) {
  return `wp-doctor-${safeHost(url).replace(/[^a-z0-9.-]/gi, '-')}-${date.toISOString().slice(0, 10)}.html`;
}

function safeHost(url) {
  try { return new URL(url).host; } catch { return String(url); }
}
